  
[**Dr. Kevin M. Moerman**](mailto:kevin.moerman@nuigalway.ie), _Lecturer in Biomedical Engineering_   

National University of Ireland Galway.   

---

\newpage

# Example 1
Consider the three truss system of Figure Q3. All trusses are linear elastic. Node 1 and node 4 are constrained from moving. Node 2 is subjected to a direct nodal force of P=1000 N in the negative x-direction. Furthermore, element 2 is subjected to a constant distributed load $X(x)=5000$ N/m.
The truss parameters for all elements are given in Table Q3.

|   | Element 1 | Element 2 | Element 3 |
| ----------- | ----------- | ----------- | ----------- |
| Youngs modulus | 200 MPa | 400 MPa | 200 MPa |
| Area | 0.02 $m^2$ | 0.01 $m^2$ | 0.02 $m^2$ |
| Length | 2 m | 2 m |  2 m |

__(a)__ Derive the element stiffness matrices as well as the global stiffness matrix.     
__(b)__ Compute the distributed load related nodal forces for element 2.  
__(c)__ Formulate the finite element equations for this system and use the finite element method to compute the nodal displacements and the direct nodal forces.  
__(d)__ To what value should the distributed load $X(x)$ be altered such that element 1 experiences zero strain.

![](trussSet_3_distributed_force.png)

## (a)

The individual element stiffness contributions are:  
$$ \begin{bmatrix} K^{(1)} \end{bmatrix}=\begin{bmatrix} K^{(3)} \end{bmatrix}=\frac{A_1 E_1}{L_1}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{200\cdot10^6 \cdot 0.02}{2}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=1\cdot10^6\begin{bmatrix} 2 & -2 \\ -2 & 2\end{bmatrix}$$ 

$$ \begin{bmatrix} K^{(2)} \end{bmatrix}=\frac{A_2 E_2}{L_2}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\frac{400\cdot10^6 \cdot 0.01}{2}\begin{bmatrix} 1 & -1 \\ -1 & 1\end{bmatrix}=\begin{bmatrix} 2 & -2 \\ -2 & 2\end{bmatrix}$$ 

Superposition provides the global stiffness matrix:   
$$\begin{bmatrix} \mathbf{K} \end{bmatrix}=1\cdot10^6\begin{bmatrix} 2 & -2  &     0 &     0 
                                                       \\ -2 &  4  & -2 &     0 
                                                       \\    0  &  -2 &  4 & -2
                                                       \\    0  &   0    & -2 &  2
                                                       \end{bmatrix}$$



In [1]:
% Numerical check
E1=200e6; E2=2*E1; E3=E1; 
A1=0.02; A2=0.01; A3=A1;
L1=2; L2=2; L3=2;
P=-1000;

I=[1 -1; -1 1];
K1=(A1*E1)/L1*I
K2=(A2*E2)/L2*I
K3=(A3*E3)/L3*I
K=zeros(4,4);
K(1:2,1:2)=K(1:2,1:2)+K1;
K(2:3,2:3)=K(2:3,2:3)+K2;
K(3:4,3:4)=K(3:4,3:4)+K3

K1 =

   2000000  -2000000
  -2000000   2000000

K2 =

   2000000  -2000000
  -2000000   2000000

K3 =

   2000000  -2000000
  -2000000   2000000

K =

   2000000  -2000000         0         0
  -2000000   4000000  -2000000         0
         0  -2000000   4000000  -2000000
         0         0  -2000000   2000000



## (b)

$${F_{dist}}^{(2-3)}=\frac{A_2 X L_2}{2} \begin{bmatrix} 1 \\ 1 \end{bmatrix}=\frac{0.01 \cdot 5000 \cdot 2}{2} \begin{bmatrix} 1 \\ 1 \end{bmatrix}=\begin{bmatrix} 50 \\ 50 \end{bmatrix}$$

In [2]:
% Numerical check
X=5000;
F_dist23=(A2*X*L2)/2*[1 1]'

F_dist23 =

   50
   50



## (c)

The total system of equations is written as: 

$$\begin{Bmatrix} F \end{Bmatrix}+\begin{Bmatrix} F \end{Bmatrix}^{dist}=\begin{bmatrix} K \end{bmatrix}\begin{Bmatrix} u \end{Bmatrix}$$   


$$\begin{Bmatrix} F_1 \\ -1000 \\ 0 \\ F_4 \end{Bmatrix}+\begin{Bmatrix} 0 \\ 50 \\ 50 \\ 0 \end{Bmatrix}=1\cdot10^6\begin{bmatrix} 2 & -2  &     0 &     0 \\ -2 &  4  & -2 &     0 \\    0  &  -2 &  4 & -2 \\    0  &   0    & -2 &  2 \end{bmatrix}\begin{Bmatrix} 0 \\ u_2 \\ u_3 \\ 0\end{Bmatrix}$$   

Leading to the following equations for $u_2$ and $u_3$: 

$$(4\cdot10^6) \cdot u_2 - (2\cdot10^6) \cdot u_3=-950$$
$$(-2\cdot10^6) \cdot u_2 + (4\cdot10^6) \cdot u_3=50$$

Adding the bottom equation twice to the top provides: 
$$(6\cdot10^6) \cdot u_3=-850 \rightarrow u_3=\frac{-850}{6\cdot10^6} \approx -1.41667\cdot10^{-4}$$

Leading to:
$$(4\cdot10^6) \cdot u_2 - (2\cdot10^6) \cdot \bigg( \frac{-850}{6\cdot10^6} \bigg)=(4\cdot10^6) \cdot u_2 +283\frac{1}{3}=-950$$

$$\rightarrow (4\cdot10^6) \cdot u_2 =-950-283\frac{1}{3}=-1233\frac{1}{3}$$

$$\rightarrow  u_2 =\frac{-1233\frac{1}{3}}{4\cdot10^6}  \approx -3.0833\cdot10^{-4}$$


Allowing for the computational of the direct forces: 

$$\begin{Bmatrix} F_1 \\ -1000 \\ 0 \\ F_4 \end{Bmatrix}+\begin{Bmatrix} 0 \\ 50 \\ 50 \\ 0 \end{Bmatrix}=1\cdot10^6\begin{bmatrix} 2 & -2  &     0 &     0 \\ -2 &  4  & -2 &     0 \\    0  & -2 &  4 & -2 \\    0  &   0    & -2 &  2 \end{bmatrix}\begin{Bmatrix} 0 \\ -3.0833\cdot10^{-4} \\ -1.41667\cdot10^{-4} \\ 0\end{Bmatrix}=\begin{Bmatrix} 616\frac{2}{3} \\ -950 \\ 50 \\ 283\frac{1}{3} \end{Bmatrix}= \begin{Bmatrix} 616\frac{2}{3} \\ -1000 \\ 0 \\ 283\frac{1}{3} \end{Bmatrix}+ \begin{Bmatrix} 0 \\ 50 \\ 50 \\ 0 \end{Bmatrix}$$


In [3]:
% Numerical check
F_dist=[0; F_dist23; 0] 

F_total2=[P+F_dist(2)]
F_total3=[0+F_dist(3)]

u3=(F_total2+2*F_total3)/((2*K(3,3))+K(2,3))
u2=( F_total2-(u3*K(2,3)) )/K(2,2)

u=[0 u2 u3 0]'
F_total=K*u
F=F_total-F_dist

F_dist =

    0
   50
   50
    0

F_total2 = -950
F_total3 =  50
u3 = -0.00014167
u2 = -0.00030833
u =

   0.00000000
  -0.00030833
  -0.00014167
   0.00000000

F_total =

   616.667
  -950.000
    50.000
   283.333

F =

    616.66667
  -1000.00000
      0.00000
    283.33333



## (d) 

Zero strain means $u_1=u_2=0$. Next we can look at the equation for the distributed force but leave the distributed force $X$ as an unknown: 

$${F_{dist}}^{(2-3)}=\frac{A_2 X L_2}{2} \begin{bmatrix} 1 \\ 1 \end{bmatrix}=\begin{bmatrix} \frac{X}{100} \\ \frac{X}{100} \end{bmatrix}$$

Next the total forces $F^{total}_2$ and $F^{total}_3$ can be expressed:

$$F^{total}_2=(4\cdot10^6) \cdot u_2 - (2\cdot10^6) \cdot u_3=\frac{X}{100}-1000$$
$$F^{total}_3=(-2\cdot10^6) \cdot u_2 + (4\cdot10^6) \cdot u_3=\frac{X}{100}$$

Adding the bottom equation twice to the top provides: 
$$(6\cdot10^6) \cdot u_3= \frac{3X}{100}-1000 \rightarrow u_3=\frac{\frac{3X}{100}-1000}{6\cdot10^6}$$


Next we obtain an expression for $u_2$:
$$(4\cdot10^6) \cdot u_2 - (2\cdot10^6) \cdot \bigg( \frac{\frac{3X}{100}-1000}{6\cdot10^6} \bigg)=\frac{X}{100}-1000$$  

Simplification: 
$$(4\cdot10^6) \cdot u_2 - \frac{1}{3}\bigg(\frac{3X}{100}-1000 \bigg)=\frac{X}{100}-1000$$

Work out multiplication of second term by $\frac{1}{3}$: 
$$(4\cdot10^6) \cdot u_2 - \frac{X}{100}+333\frac{1}{3}=\frac{X}{100}-1000$$

Add $\frac{X}{100}-333\frac{1}{3}$: 
$$(4\cdot10^6) \cdot u_2 =\frac{2X}{100}-1333\frac{1}{3}$$

Divide by $4\cdot10^6$ to obtain expression for $u_2$ and set to zero: 
$$u_2 =10^{-6} \cdot \bigg( \frac{X}{200}-333\frac{1}{3} \bigg)=0$$

Divide by $10^{-6}$: 
$$\frac{X}{200}-333\frac{1}{3}=0$$

Add $333\frac{1}{3}$: 
$$\frac{X}{200}=333\frac{1}{3}$$

Solve by multiplying by 200: 
$$\rightarrow X=66666 \frac{2}{3}$$


In [4]:
% Numerical check
X=-200/3*P
F_dist23=[X/100 X/100]';
F_dist=[0; F_dist23; 0]

F_total2=[P+F_dist(2)];
F_total3=[0+F_dist(3)];
u3=(F_total2+2*F_total3)/((2*K(3,3))+K(2,3))
u2=( F_total2-(u3*K(2,3)) )/K(2,2)

u=[0 u2 u3 0]'
F_total=K*u
F=F_total-F_dist

X =  66666.66667
F_dist =

     0.00000
   666.66667
   666.66667
     0.00000

u3 =  0.00016667
u2 =    4.2633e-20
u =

   0.00000000
   0.00000000
   0.00016667
   0.00000000

F_total =

  -8.5265e-14
  -3.3333e+02
   6.6667e+02
  -3.3333e+02

F =

     -0.00000
  -1000.00000
      0.00000
   -333.33333

